import {existsSync} from 'node:fs';
import {mkdir,writeFile} from 'node:fs/promises';
const dir=new URL('../src/brand/',import.meta.url);await mkdir(dir,{recursive:true});
const navy='#0c2633',teal='#007f76';
const symbol=(n,color)=>n===1?`<g fill="none" stroke="${color}" stroke-width="5" stroke-linecap="round"><path d="M13 20A24 24 0 0 1 54 33"/><path d="M51 44A24 24 0 0 1 10 31"/><path d="M20 46C37 47 46 34 43 18"/></g>`:n===2?`<path fill="${color}" fill-rule="evenodd" d="M32 5a27 27 0 1 1 0 54 27 27 0 0 1 0-54zM23 18v28h9c10 0 16-5 16-14s-6-14-16-14z"/>`:`<g fill="none" stroke="${color}" stroke-width="7"><path d="M49 15A24 24 0 1 0 54 23"/></g>`;
const wordmark=(n,color,accent)=>n===3?`<g fill="${color}" font-family="Inter,Arial,sans-serif" font-size="36" font-weight="550" letter-spacing="-1.4"><text x="0" y="43">Data</text><g transform="translate(77,13) scale(.49)">${symbol(3,accent)}</g><text x="110" y="43">rb Cloud</text></g>`:`<g transform="translate(0,1) scale(.8)">${symbol(n,accent)}</g><text x="65" y="43" fill="${color}" font-family="Inter,Arial,sans-serif" font-size="36" font-weight="550" letter-spacing="-1.4">Dataorb Cloud</text>`;
for(const n of [1,2,3])for(const [variant,color,accent] of [['color',navy,teal],['black','#000','#000'],['white','#fff','#fff']]){
  await writeFile(new URL(`direction-${n}-${variant}.svg`,dir),`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 330 64" role="img" aria-label="Dataorb Cloud logo direction ${n}">${wordmark(n,color,accent)}</svg>`);
  await writeFile(new URL(`direction-${n}-symbol-${variant}.svg`,dir),`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="Dataorb Cloud symbol direction ${n}">${symbol(n,accent)}</svg>`);
}
const title=['Arc Orb','Negative-space D','Signature O'];
const subtitle=['Three arcs. One point of connection.','A simple silhouette, a letter within.','A quiet wordmark with a distinct O.'];
let board=`<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="1140" viewBox="0 0 1440 1140"><rect width="1440" height="1140" fill="#f1f5f5"/><g font-family="Inter,Arial,sans-serif"><text x="50" y="57" font-size="16" fill="${teal}" letter-spacing="2">DATAORB CLOUD / BRAND EXPLORATION</text><text x="50" y="111" font-size="39" fill="${navy}" letter-spacing="-1.5">Three directions. One clear identity.</text><text x="50" y="149" font-size="15" fill="#53666f">Original hand-authored vector studies · Not generated with image 2.5 · Website retains a temporary text logo</text>`;
for(let i=0;i<3;i++){
 const x=50+i*453,n=i+1;
 board+=`<g transform="translate(${x},190)"><text y="20" font-size="13" fill="${teal}">0${n}</text><text y="59" font-size="27" fill="${navy}">${title[i]}</text><text y="88" font-size="14" fill="#53666f">${subtitle[i]}</text><rect y="116" width="432" height="184" rx="3" fill="white"/><text x="18" y="142" font-size="10" fill="#61747c" letter-spacing="1.4">LIGHT / NAVY + TEAL</text><g transform="translate(${n===3?73:34},186) scale(${n===3?1.07:1})">${wordmark(n,navy,teal)}</g><rect y="312" width="432" height="184" rx="3" fill="${navy}"/><text x="18" y="339" font-size="10" fill="#bbd2d8" letter-spacing="1.4">DARK / REVERSED</text><g transform="translate(${n===3?73:34},384) scale(${n===3?1.07:1})">${wordmark(n,'#fff','#fff')}</g><text y="533" font-size="10" fill="#61747c" letter-spacing="1.4">WEBSITE NAVIGATION / 64 PX HEIGHT</text><rect y="550" width="432" height="64" fill="white" stroke="#d8e1e3"/><g transform="translate(16,568) scale(.46)">${wordmark(n,navy,teal)}</g><text x="227" y="588" font-size="10" fill="${navy}">Services</text><rect x="300" y="567" width="115" height="31" rx="2" fill="${navy}"/><text x="313" y="587" fill="white" font-size="10">Request a Quote ↗</text><text y="652" font-size="10" fill="#61747c" letter-spacing="1.4">FAVICON / ACTUAL DISPLAY SIZES</text>`;
 let fx=17;for(const size of [16,24,32]){board+=`<g transform="translate(${fx},677) scale(${size/64})">${symbol(n,teal)}</g><text x="${fx}" y="732" font-size="11" fill="#61747c">${size}px</text>`;fx+=67;}
 board+=`<rect x="243" y="666" width="189" height="80" rx="3" fill="${navy}"/><g transform="translate(266,689) scale(.5)">${symbol(n,'#fff')}</g><text x="315" y="711" font-size="11" fill="#c5d4d8">Reversed / 32px</text><text y="785" font-size="10" fill="#61747c" letter-spacing="1.4">ONE-COLOR / BLACK + WHITE</text><rect y="803" width="211" height="84" fill="white"/><rect x="221" y="803" width="211" height="84" fill="#000"/><g transform="translate(18,830) scale(.49)">${wordmark(n,'#000','#000')}</g><g transform="translate(239,830) scale(.49)">${wordmark(n,'#fff','#fff')}</g></g>`;
}
board+=`<text x="50" y="1120" font-size="11" fill="#53666f">PALETTE  Navy #0C2633  /  Teal #007F76  /  White #FFFFFF      •      Symbols are vector paths; wordmark text remains editable. Final type outlining follows selection.</text></g></svg>`;
await writeFile(new URL('comparison.svg',dir),board);
if (!existsSync(new URL('../src/assets/dataorb-cloud-final.png', import.meta.url))) await writeFile(new URL('index.html',dir),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Dataorb Cloud — Logo exploration</title><style>body{margin:0;background:#f1f5f5;font:15px/1.6 Arial;color:#0c2633}header{padding:20px 3.5%;display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}a{color:inherit}img{display:block;width:100%;height:auto}section{padding:25px 3.5%;max-width:900px}a:focus-visible{outline:3px solid #007f76;outline-offset:5px}</style><header><a href="/">← Website</a><a href="comparison.svg" download>Download SVG comparison board</a><a href="prompts.md">External image-generation prompts</a></header><main><img src="comparison.svg" alt="Three Dataorb Cloud logo studies: Arc Orb, Negative-space D and Signature O. Each appears on light and dark backgrounds, in a navigation bar, at 16, 24 and 32 pixel favicon sizes, and in black and white."><section><p>These are original, hand-authored vector concept studies, not image-generated results. The website uses a temporary text logo. The SVG symbols are paths; the logo lettering remains editable text using Inter, with Arial fallback. Choose a direction before final optical refinement and outlining.</p><p>Suggested starting point: 02 / Negative-space D for a strong small-scale silhouette. 01 feels more connected and fluid; 03 puts the company name first.</p></section></main></html>`);
console.log('Created original SVG studies and comparison board.');
